// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLkPdBafrbMHzWKa1lqL4i5RRPVt79_0s',
    appId: '1:251940649994:web:c9c80b3c92943d156333f3',
    messagingSenderId: '251940649994',
    projectId: 'pokedex-dbb80',
    authDomain: 'pokedex-dbb80.firebaseapp.com',
    storageBucket: 'pokedex-dbb80.firebasestorage.app',
    measurementId: 'G-KKVMDXQV1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFmg4os5NnsbvPOqKAOtDwOsv4wA_JBjA',
    appId: '1:251940649994:android:f4c5b3fa06d3cf2a6333f3',
    messagingSenderId: '251940649994',
    projectId: 'pokedex-dbb80',
    storageBucket: 'pokedex-dbb80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdafo3UumbGwxxqYMAyCuVL7O_qjSMRJ8',
    appId: '1:251940649994:ios:e7b8aa413cf1ffad6333f3',
    messagingSenderId: '251940649994',
    projectId: 'pokedex-dbb80',
    storageBucket: 'pokedex-dbb80.firebasestorage.app',
    iosBundleId: 'com.navidrahman.pokedex.pokedex',
  );
}
